// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // Manual sidebar for Module 1: The Robotic Nervous System (ROS 2)
  roboticsModuleSidebar: [
    {
      type: 'category',
      label: 'Module 1: The Robotic Nervous System (ROS 2)',
      link: {type: 'doc', id: 'robotics-module-one/index'},
      items: [
        {
          type: 'category',
          label: 'Chapter 1: ROS 2 Core Concepts',
          link: {type: 'doc', id: 'robotics-module-one/chapter-1/index'},
          items: [
            'robotics-module-one/chapter-1/lesson-1',
            'robotics-module-one/chapter-1/lesson-2',
            'robotics-module-one/chapter-1/lesson-3',
          ],
        },
        {
          type: 'category',
          label: 'Chapter 2: Python & ROS 2 (rclpy)',
          link: {type: 'doc', id: 'robotics-module-one/chapter-2/index'},
          items: [
            'robotics-module-one/chapter-2/lesson-1',
            'robotics-module-one/chapter-2/lesson-2',
            'robotics-module-one/chapter-2/lesson-3',
          ],
        },
        {
          type: 'category',
          label: 'Chapter 3: Unified Robot Description Format (URDF)',
          link: {type: 'doc', id: 'robotics-module-one/chapter-3/index'},
          items: [
            'robotics-module-one/chapter-3/lesson-1',
            'robotics-module-one/chapter-3/lesson-2',
            'robotics-module-one/chapter-3/lesson-3',
          ],
        },
        {
          type: 'category',
          label: 'Chapter 4: Advanced ROS 2 Concepts',
          link: {type: 'doc', id: 'robotics-module-one/chapter-4/index'},
          items: [
            'robotics-module-one/chapter-4/lesson-1',
            'robotics-module-one/chapter-4/lesson-2',
            'robotics-module-one/chapter-4/lesson-3',
          ],
        },
      ],
    },
  ],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
